// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/common/BaseModal.vue')['default']
    CalendarDouble: typeof import('./src/components/common/calendarDouble.vue')['default']
    ChangeItems: typeof import('./src/components/common/changeItems.vue')['default']
    CommonImg: typeof import('./src/components/common/CommonImg.vue')['default']
    CommonPagination: typeof import('./src/components/common/CommonPagination.vue')['default']
    CommonSearch: typeof import('./src/components/common/CommonSearch.vue')['default']
    CommonSearchItem: typeof import('./src/components/common/CommonSearchItem.vue')['default']
    CommonTable: typeof import('./src/components/common/CommonTable.vue')['default']
    DatePicker: typeof import('./src/components/common/datePicker.vue')['default']
    DelModal: typeof import('./src/components/common/DelModal.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    FormItem: typeof import('./src/components/common/formItem.vue')['default']
    FormWrap: typeof import('./src/components/common/formWrap.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    ImageWrapper: typeof import('./src/components/common/imageWrapper.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    PdfWrapper: typeof import('./src/components/common/pdfWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderItem: typeof import('./src/components/layout/SliderItem.vue')['default']
    TimePicker: typeof import('./src/components/common/timePicker.vue')['default']
    ToggleScreen: typeof import('./src/components/layout/toggleScreen.vue')['default']
    Upload: typeof import('./src/components/common/Upload.vue')['default']
  }
}
