// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
		Icon: typeof import('./components/Icon/index.vue')['default'];
		Layout: typeof import('./components/layout/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		SliderItem: typeof import('./components/layout/SliderItem.vue')['default'];
	}
}
